// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Connect(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function GetPeers():Promise<Array<main.PeerView>>;

export function GetSelf():Promise<main.PeerView>;

export function GetStatus():Promise<string>;

export function IsTunActive():Promise<boolean>;

export function JoinRoom(arg1:string,arg2:string):Promise<void>;

export function LeaveRoom():Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function PingServer(arg1:string):Promise<number>;

export function RestartAsAdmin():Promise<void>;

export function SendChat(arg1:string):Promise<void>;

export function SendVoiceToAll(arg1:Array<number>):Promise<void>;
