// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetPeers() {
  return window['go']['main']['App']['GetPeers']();
}

export function GetSelf() {
  return window['go']['main']['App']['GetSelf']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function IsTunActive() {
  return window['go']['main']['App']['IsTunActive']();
}

export function JoinRoom(arg1, arg2) {
  return window['go']['main']['App']['JoinRoom'](arg1, arg2);
}

export function LeaveRoom() {
  return window['go']['main']['App']['LeaveRoom']();
}

export function PingServer(arg1) {
  return window['go']['main']['App']['PingServer'](arg1);
}

export function RestartAsAdmin() {
  return window['go']['main']['App']['RestartAsAdmin']();
}

export function SendChat(arg1) {
  return window['go']['main']['App']['SendChat'](arg1);
}
