// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetPeers() {
  return window['go']['main']['App']['GetPeers']();
}

export function GetSelf() {
  return window['go']['main']['App']['GetSelf']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function IsTunActive() {
  return window['go']['main']['App']['IsTunActive']();
}

export function JoinRoom(arg1, arg2) {
  return window['go']['main']['App']['JoinRoom'](arg1, arg2);
}

export function LeaveRoom() {
  return window['go']['main']['App']['LeaveRoom']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function PingServer(arg1) {
  return window['go']['main']['App']['PingServer'](arg1);
}

export function RestartAsAdmin() {
  return window['go']['main']['App']['RestartAsAdmin']();
}

export function SendChat(arg1) {
  return window['go']['main']['App']['SendChat'](arg1);
}

export function SendVideoToAll(arg1) {
  return window['go']['main']['App']['SendVideoToAll'](arg1);
}

export function SendVoiceToAll(arg1) {
  return window['go']['main']['App']['SendVoiceToAll'](arg1);
}

export function SetTrayMenuState(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetTrayMenuState'](arg1, arg2, arg3, arg4);
}

export function SetVoiceStatus(arg1, arg2) {
  return window['go']['main']['App']['SetVoiceStatus'](arg1, arg2);
}

export function TestServer(arg1) {
  return window['go']['main']['App']['TestServer'](arg1);
}
